//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSITSolutions.ContactSite.Client.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TSITSolutions.ContactSite.Client.Shared.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thomas Schulze IT Solutions.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mein Name ist Thomas Schulze, ich bin freiberuflicher Softwareentwickler und Architekt..
        /// </summary>
        public static string IndexMeLine1 {
            get {
                return ResourceManager.GetString("IndexMeLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meine Leidenschaft ist die Entwicklung von leicht erweiterbaren Lösungen, die vor allem durch ihre Architektur
        ///und User Experience herausstechen. Seien es dabei Microservices mit gut und transparent definierten und
        ///dokumentierten REST-APIs oder auch Event-getriebene serverlose Lösungen in der Cloud. An erster Stelle
        ///steht für mich immer der größtmögliche Wert für die Benutzer. Genauso wichtig ist es mir, kontinuierlich genau
        ///diesen Wert in kurzen Feedbackschleifen mit etablierten DevOps-Praktiken zu lie [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IndexMeLine2Part1 {
            get {
                return ResourceManager.GetString("IndexMeLine2Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontinuierlicher Wissensaustausch sowie die Verbesserung der Prozesse inner- und außerhalb agiler Teams,
        ///Clean Code und Architekturthemen sind ein großer Teil meines Interessengebietes..
        /// </summary>
        public static string IndexMeLine2Part2 {
            get {
                return ResourceManager.GetString("IndexMeLine2Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technisch zuhause fühle ich mich in allen Bereichen von Microsoft .NET (C#, ASP.NET Core 6 APIs, Hosted
        ///Services als Backend, Azure Functions, AWS Lambdas etc.) und Azure. Kleinere Ausflüge mit Blazor WASM,
        ///Angular und React haben mich aber auch für die Entwicklung von „Mobile First“-Webseiten begeistert..
        /// </summary>
        public static string IndexMeLine3Part1 {
            get {
                return ResourceManager.GetString("IndexMeLine3Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herzlich willkommen.
        /// </summary>
        public static string IndexWelcomeMessage {
            get {
                return ResourceManager.GetString("IndexWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impressum.
        /// </summary>
        public static string LegalInformationPageTitle {
            get {
                return ResourceManager.GetString("LegalInformationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aus.
        /// </summary>
        public static string Main_DarkMode_Off {
            get {
                return ResourceManager.GetString("Main_DarkMode_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An.
        /// </summary>
        public static string Main_DarkMode_On {
            get {
                return ResourceManager.GetString("Main_DarkMode_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode ist.
        /// </summary>
        public static string Main_DarkMode_Text {
            get {
                return ResourceManager.GetString("Main_DarkMode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startseite.
        /// </summary>
        public static string NavigationHome {
            get {
                return ResourceManager.GetString("NavigationHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impressum.
        /// </summary>
        public static string NavigationLegalInformation {
            get {
                return ResourceManager.GetString("NavigationLegalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekte.
        /// </summary>
        public static string NavigationProjects {
            get {
                return ResourceManager.GetString("NavigationProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to heute.
        /// </summary>
        public static string Projects_Timeline_today {
            get {
                return ResourceManager.GetString("Projects_Timeline_today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Projects_Toolbar_Filter {
            get {
                return ResourceManager.GetString("Projects_Toolbar_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekte.
        /// </summary>
        public static string ProjectsHeader {
            get {
                return ResourceManager.GetString("ProjectsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekte.
        /// </summary>
        public static string ProjectsPageTitle {
            get {
                return ResourceManager.GetString("ProjectsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade....
        /// </summary>
        public static string Shared_Loading {
            get {
                return ResourceManager.GetString("Shared_Loading", resourceCulture);
            }
        }
    }
}
