name: CI build

on:
  pull_request:
    branches: 
    - main

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3.0.0
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore ./site/TSITSolutions.ContactSite.sln

    - name: Build
      run: dotnet build ./site/TSITSolutions.ContactSite.sln --no-restore
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
