name: CI build

on:
  pull_request:
    branches: 
    - main

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.2.0
      with:
        dotnet-version: 8.0.x
        
    - name: install wasm tools
      run: dotnet workload install wasm-tools

    - name: Restore dependencies
      run: dotnet restore ./site/TSITSolutions.ContactSite.sln

    - name: Build
      run: dotnet build ./site/TSITSolutions.ContactSite.sln --no-restore
    
    - name: Test with Coverage
      run: |
        dotnet test ./site/TSITSolutions.ContactSite.sln --no-build --verbosity normal \
        /p:CollectCoverage=true /p:CoverletOutput=./coverage/ \
        /p:CoverletOutputFormat=opencover
        
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage/coverage.opencover.xml
        fail_ci_if_error: true
        verbose: true
