name: Build and Deploy to App Service

on:
  push:
    branches:
      - main
    paths:
      - 'site/**'
  workflow_dispatch:

permissions:
  contents: read
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: '8.0.x'
      
      - name: restore wasm-tools
        run: dotnet workload restore ./site/TSITSolutions.ContactSite.sln

      - name: dotnet publish
        run: dotnet publish ./site/src/Server/TSITSolutions.ContactSite.Server.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ase-contactsite-website-prod-westeurope'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
